- name: Deploy basic (but awesome) web server
  hosts: all
  vars:
    index_title: Awesome web server
    index_content: |
                This is {{ ansible_hostname | upper }}
                <br>Hello Montauban ! This web server was installed with Ansible Tower
    
  tasks:
  - name: Enforce Red Hat Subscription Manager present
    yum:
      name: 
        - subscription-manager
        - firewalld

  - name: Register system into RHSM
    redhat_subscription:
      state: present
      username: "{{ rhsm_username }}"
      password: "{{ rhsm_password }}"
      pool_ids:  "{{ rhsm_poolid }}"
      force_register: no
  
  - name: httpd package is present
    yum:
      name: httpd

  - name: latest index.html file is present
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: apache
      group: apache

  - name: httpd is started
    service:
      name: httpd
      state: started
